### ISSUE TITLE
Proposed Edits to philipkiely.com

### ISSUE THREAD

**Issue by joelchoi00** [philipkiely/philipkiely.com#3]
**Front Page**

- Being able to play around with different visuals for your picture is fun but the second filter doesn't look very good and just seems like a grainier version of your original one
- When I hover over the social media symbols on the top right, we can have them indicate which website it is (I didn't know the "g" was goodreads or "y" was ycombinator)

**Essays, Codes, Notes**

- Put a header to explain briefly what each of these is
- Put the subscriber bar at the end because it looks more like a search engine right now; preface it with something like "Looking for more?/ Did you enjoy? Subscribe here!" 

**CEfIP**

- Video series and 30-day email course look like clickable links so maybe say "includes" above
- For "What's in the Course?", use the same image you did for 12-part vid course above
- This may be on purpose since I also saw this on WfSD, but is it supposed to be repetitive with similar info introduced again and again? 
- Put the squiggly background on "Reviews" or switch the order so that the timeline and the reviews don't blend

**Products**

- Zoom out when mouse hovers so the entire cover is shown
- WPTW should just use the computer + text = money logo rather than a screenshot of the website
- The Office Hours picture looks unprofessional; recommend getting a new image
- Rough Drafts: picture is cool but doesn't fit with other drawings
- All in all the style is too inconsistent throughout each square

**WfSD**

- Same note as CEfIP; feels repetitive with the twitter reviews and the "Get Now!" message. I just tend to skip over the minute changes between each of them because I feel I've already seen this.
- Put the Questions section at the end because "Want to learn first?" might answer questions they had

**Comment by philipkiely** [comment]
Thank you for the notes! Here is what I will do:

Front Page

* Replace second filter with B&W version as a callback to V2 of the site.
* Tooltips over the social sites is interesting, but the idea of that section is that people click on whichever platform they favor to find me on. Also I am most likely removing those two when I upgrade to a different icon pack. No change.

Essays:

* Great idea
* Great idea. I'm actually going to refresh these pages and the subscriber experience soon and will take this under consideration when I do.

CEfIP

* Maybe they should be clickable ... pop up a modal with more info
* Good Idea
* Yes, sales pages reiterate important points
* Give "reviews" the same light grey background as FAQ

Products:

* Cool Idea, I still need to fix up how these work overall 
* Yes
* And guess where that image is coming from...
* See above...
* This sounds like a Joel Choi problem

WfSD

* Repeated CTAs are very important
* I think I should instead change the header on that section ... I don't want people leaving the page to listen to a 1-hour podcast and get distracted unless they have reached the end of the page and still aren't convinced.
